# Tutorial 0: Python Review

### Programming, Linear Algebra, & Multi-variable Calculus

A quick refresher of the tools we'll need for this course.

*You already know these concepts — this is just how they look in Python.*


# Part 1
## Basic Programming Concepts in Python


## Variables & Immutable Primitives

Python's built-in immutable types. **Everything is an object** — even `int` and `None`. No type declaration needed.


In [1]:
x = 42          # int
y = 3.14        # float
s = "hello"     # str
b = True        # bool
c = 2 + 3j      # complex
n = None        # NoneType

print(type(x), type(y), type(s), type(b), type(c))


<class 'int'> <class 'float'> <class 'str'> <class 'bool'> <class 'complex'>


## Type Casting & Inspection

Built-in converters: `int()`, `float()`, `str()`, `bool()`, `ord()`, `chr()`. Identity and type checks: `type()`, `isinstance()`, `id()`.


In [2]:
int("42")          # 42
float("3.14")      # 3.14
str(42)            # "42"
bool(0), bool(1)   # (False, True)
ord("A"), chr(65)  # (65, "A")

# type() vs isinstance() — isinstance is usually preferred
print(type(42) == int)         # True
print(isinstance(42, int))     # True
print(isinstance(True, int))   # True — bool is a subclass of int!

# Every object has a unique identity
print(id([1, 2, 3]))


True
True
True
2238937839488


## Data Structures: Tuples (Immutable)

Fixed-size, ordered, heterogeneous. Common for returning multiple values from a function.


In [38]:
t = (1, 2, 3)
print(t[0])           # 1
# t[0] = 99           # TypeError

# Unpacking
a, b, c = t
print(a, b, c)

# Single-element tuple needs a trailing comma
solo = (5,)


1
1 2 3


## Data Structures: Lists, Dicts, Sets (Mutable)


In [42]:
# list — ordered, indexable, allows duplicates
lst = [1, 2, 3]
lst.append(4)
lst.insert(1, 0)
print(lst)                 # [0, 1, 2, 3, 4]

# dict — key-value pairs
d = {"name": "Alice", "age": 30}
d["age"] = 31
print(d.keys(), d.values())

# set — unordered, unique elements
s = {5, "b", 3, "a", 2}
s.add(4)
print(s)                   # {1, 2, 3, 4}


[1, 0, 2, 3, 4]
dict_keys(['name', 'age']) dict_values(['Alice', 31])
{2, 3, 4, 5, 'b', 'a'}


## Indexing & Slicing

Syntax: `seq[start:stop:step]`. Works on lists, tuples, strings, and more. Negative indices count from the end.


In [5]:
lst = [0, 10, 20, 30, 40, 50]

print(lst[0])      # 0       (first)
print(lst[-1])     # 50      (last)
print(lst[1:4])    # [10, 20, 30]
print(lst[:3])     # [0, 10, 20]
print(lst[3:])     # [30, 40, 50]
print(lst[::2])    # [0, 20, 40]   — every 2nd
print(lst[::-1])   # reversed


0
50
[10, 20, 30]
[0, 10, 20]
[30, 40, 50]
[0, 20, 40]
[50, 40, 30, 20, 10, 0]


## Python's Memory Model

Every variable is a **reference** to an object. Assignment copies the *reference*, not the data.


In [44]:
a = [1, 2, 3]
b = a              # b and a point to THE SAME list
b.append(4)

print("a:", a)     # [1, 2, 3, 4]  ← a changed too!
print("b:", b)     # [1, 2, 3, 4]
print(a is b)      # True

c=2
d=c
c=4
print(c)


a: [1, 2, 3, 4]
b: [1, 2, 3, 4]
True
4


## Making Actual Copies

To get a new list, be explicit. For nested structures, you need `deepcopy`.


In [7]:
import copy

a = [1, 2, 3]
b = a.copy()       # or list(a), or a[:]
b.append(4)
print(a, b)        # [1, 2, 3]  [1, 2, 3, 4]

# Nested structures need deepcopy, or the inner lists are still shared
nested = [[1, 2], [3, 4]]
shallow = nested.copy()
deep = copy.deepcopy(nested)

shallow[0].append(99)
print("nested after shallow edit:", nested)   # inner list was shared!


[1, 2, 3] [1, 2, 3, 4]
nested after shallow edit: [[1, 2, 99], [3, 4]]


## Numeric Operators


In [8]:
print(7 + 3)       # 10
print(7 - 3)       # 4
print(7 * 3)       # 21
print(7 / 3)       # 2.333...   (true division, always float)
print(7 // 3)      # 2           (floor division)
print(7 % 3)       # 1           (modulo)
print(2 ** 10)     # 1024        (exponentiation)


10
4
21
2.3333333333333335
2
1
1024


## Logical & Comparison Operators

Keywords, not symbols: `and`, `or`, `not`. Plus `is`, `in`, `any`, `all`.


In [9]:
# Comparison: ==, !=, <, >, <=, >=
# Logical:    and, or, not
# Identity:   is, is not       (same object?)
# Membership: in, not in

a, b = [1, 2, 3], [1, 2, 3]
print(a == b)       # True  — equal values
print(a is b)       # False — different objects

print(2 in a)                    # True
print(all([True, True, False]))  # False
print(any([False, False, True])) # True


True
False
True
False
True


## Bitwise Operators


In [ ]:
print(bin(0b1100 & 0b1010))   # '0b1000'  AND
print(bin(0b1100 | 0b1010))   # '0b1110'  OR
print(bin(0b1100 ^ 0b1010))   # '0b110'   XOR
print(bin(0b0001 << 3))       # '0b1000'  left shift
print(bin(0b1000 >> 2))       # '0b10'    right shift
print(~5)                     # -6        bitwise NOT (two's complement)


0b1000
0b1110
0b110
0b1000
0b11
-6


## Assignment & Order of Operations

Every arithmetic/bitwise op has a compound-assignment form: `+=`, `-=`, `*=`, `//=`, `**=`, `&=`, `|=`, …


In [11]:
x = 10
x += 5       # 15
x -= 2       # 13
x *= 2       # 26
x //= 5      # 5
x **= 2      # 25
print(x)


25


Precedence (roughly): `**` → unary `-` → `* / // %` → `+ -` → shifts → bitwise → comparisons → `not` → `and` → `or`. **When in doubt, use parentheses.**

## String Declaration

Four quoting styles. Triple quotes allow multi-line strings.


In [12]:
s1 = 'single quotes'
s2 = "double quotes"
s3 = '''triple-single
can span
multiple lines'''
s4 = """triple-double also multi-line"""

print(s3)


triple-single
can span
multiple lines


## Escape Characters & Raw Strings

Raw strings (`r"..."`) disable escape processing — handy for regex and Windows paths.


In [13]:

print("tab\there")           # tab
print("line1\nline2")        # newline
print("she said \"hi\"")     # escaped quote
print("back\\slash")         # literal backslash

# Raw strings — escapes NOT interpreted
print(r"C:\new_folder\tmp")  # C:\new_folder\tmp


tab	here
line1
line2
she said "hi"
back\slash
C:\new_folder\tmp


## String Methods & Concatenation

Strings are immutable — these methods return *new* strings. Use `+` to concatenate.


In [53]:
s = "  Hello, World!  "
a=1
print(s.strip())                   # "Hello, World!"
print(s.lower())
print(s.strip().split(","))        # ["Hello", " World!"]
print(",".join(["a", "b", "c"]))   # "a,b,c"

print("abc123".isalpha())          # False
print("abc".isalpha())             # True
print(s.startswith("  Hello"))     # True
print("ell" in s)                  # True

print("Hello "+str(a) + "World")          # concatenation


Hello, World!
  hello, world!  
['Hello', ' World!']
a,b,c
False
True
True
True
Hello 1World


## String Formatting: f-strings (Preferred)

f-strings are the modern default. Use the format mini-language for numeric precision.


In [15]:
name, age, pi = "Alice", 30, 3.14159

print(f"I'm {name}, age {age}.")

# Numeric formatting mini-language
print(f"{pi:.2f}")       # '3.14'        fixed, 2 decimals
print(f"{pi:.3e}")       # '3.142e+00'   scientific
print(f"{1_000_000:,}")  # '1,000,000'   thousands separator
print(f"{0.75:.0%}")     # '75%'         percentage
print(f"{42:>6}")        # '    42'      right-aligned, width 6

# Legacy forms (you'll see these in older code):
print("{}, {}".format(name, age))
print("%s, %d" % (name, age))


I'm Alice, age 30.
3.14
3.142e+00
1,000,000
75%
    42
Alice, 30
Alice, 30


## Conditionals: if / elif / else

Indentation is syntactically significant — no braces.


In [16]:
x = 10

if x > 0:
    print("positive")
elif x < 0:
    print("negative")
else:
    print("zero")


positive


## Ternary Expression & Truthiness

**Falsy:** `None`, `False`, `0`, `0.0`, `""`, `[]`, `{}`, `set()`. Everything else is truthy.


In [55]:
# Ternary expression
x = 7
label = "even" if x % 2 == 0 else "odd"
print(label)

if []:
    print("won't print")
if [0]:
    print("prints — non-empty list is truthy")

# Short-circuit fallback idiom
name = ""
display = name or "anonymous"
print(display)                  # 'anonymous'


odd
prints — non-empty list is truthy
anonymous


## Match / Case  (Python 3.10+)

Structural pattern matching — more powerful than C-style switches.


In [18]:
def describe(x):
    match x:
        case 0:
            return "zero"
        case 1 | 2 | 3:
            return "small"
        case int() if x > 100:
            return "large"
        case [a, b]:
            return f"pair ({a}, {b})"
        case _:
            return "other"

for v in [0, 2, 200, [1, 2], "hi"]:
    print(v, "->", describe(v))


0 -> zero
2 -> small
200 -> large
[1, 2] -> pair (1, 2)
hi -> other


## Iterables & For Loops

An **iterable** is anything you can `for`-loop over: lists, tuples, strings, dicts, sets, files, generators, …


In [19]:
for ch in "abc":
    print(ch)

for num in [10, 20, 30]:
    print(num)

# Dicts iterate KEYS by default
for key in {"a": 1, "b": 2}:
    print(key)

for k, v in {"a": 1, "b": 2}.items():
    print(k, "->", v)


a
b
c
10
20
30
a
b
a -> 1
b -> 2


## range, enumerate, zip

Essential helpers for common loop patterns.


In [20]:
for i in range(3):              # 0, 1, 2
    print(i)

for i in range(2, 11, 2):       # 2, 4, 6, 8, 10
    print(i)

# enumerate: (index, value)
for i, val in enumerate(["a", "b", "c"]):
    print(i, val)

# zip: walk multiple iterables in parallel
for x, y in zip([1, 2, 3], ["a", "b", "c"]):
    print(x, y)


0
1
2
2
4
6
8
10
0 a
1 b
2 c
1 a
2 b
3 c


## While Loops, continue, break


In [21]:
i = 0
while i < 10:
    i += 1
    if i == 3:
        continue        # skip the rest of this iteration
    if i == 7:
        break           # exit the loop entirely
    print(i)
# Prints: 1 2 4 5 6


1
2
4
5
6


## List Comprehensions

A concise way to build a list from an iterable.
Form: `[expr for item in iterable if condition]`


In [22]:
squares = [x**2 for x in range(6)]
print(squares)                          # [0, 1, 4, 9, 16, 25]

evens = [x for x in range(10) if x % 2 == 0]
print(evens)                            # [0, 2, 4, 6, 8]

# Nested: produces 2D list
matrix = [[i * j for j in range(3)] for i in range(3)]
print(matrix)


[0, 1, 4, 9, 16, 25]
[0, 2, 4, 6, 8]
[[0, 0, 0], [0, 1, 2], [0, 2, 4]]


## Dict & Set Comprehensions


In [23]:
# Dict comprehension
square_map = {x: x**2 for x in range(5)}
print(square_map)

# Set comprehension (dedupes automatically)
word_lengths = {len(w) for w in ["hi", "bye", "hello", "yo"]}
print(word_lengths)                     # {2, 3, 5}

# With filtering
ages = {"Alice": 30, "Bob": 12, "Cara": 25}
adults = {name: age for name, age in ages.items() if age >= 18}
print(adults)


{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}
{2, 3, 5}
{'Alice': 30, 'Cara': 25}


## Function Declaration

Header: `def name(positional, keyword=default) -> ReturnType:`. Type annotations and docstrings are optional but strongly recommended.


In [24]:
def greet(name: str, greeting: str = "Hello") -> str:
    """Return a friendly greeting.

    Args:
        name:     The person's name.
        greeting: Optional salutation.
    """
    return f"{greeting}, {name}!"

print(greet("Alice"))
print(greet("Bob", greeting="Hi"))


Hello, Alice!
Hi, Bob!


## `*args`, `**kwargs`, and Unpacking

`*args` collects extra positional args into a tuple; `**kwargs` collects extra keyword args into a dict. Use `*` and `**` on a call site to *unpack* a sequence/dict into arguments.


In [25]:
def report(label, *args, **kwargs):
    print("label:", label)
    print("args:", args)
    print("kwargs:", kwargs)

report("demo", 1, 2, 3, color="red", size=12)

# Unpacking
def add3(a, b, c):
    return a + b + c

nums = [1, 2, 3]
opts = {"a": 1, "b": 2, "c": 3}
print(add3(*nums))    # 6
print(add3(**opts))   # 6

# pass — no-op placeholder body
def todo():
    pass


label: demo
args: (1, 2, 3)
kwargs: {'color': 'red', 'size': 12}
6
6


## Errors: raise and assert

`raise` throws an exception; `assert` is for invariants/debugging (and is skipped when Python runs with `-O`).

Common types: `TypeError`, `ValueError`, `IndexError`, `KeyError`, `AttributeError`, `ZeroDivisionError`, `FileNotFoundError`, …


In [26]:
def divide(a, b):
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b

def sqrt(x):
    assert x >= 0, "x must be non-negative"
    return x ** 0.5

print(sqrt(9))
# divide(1, 0)   # would raise ValueError


3.0


## try / except / finally

`try` attempts code, `except` catches specific errors, `else` runs when no error was raised, `finally` always runs (cleanup).


In [27]:
def safe_divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError as e:
        print(f"Caught: {e}")
        return None
    except (TypeError, ValueError) as e:
        print(f"Bad input: {e}")
        return None
    else:
        print("No error occurred")
        return result
    finally:
        print("This always runs (cleanup happens here)")

safe_divide(10, 0)
print("---")
safe_divide(10, 2)


Caught: division by zero
This always runs (cleanup happens here)
---
No error occurred
This always runs (cleanup happens here)


5.0

## File I/O

`with open(...)` — the file closes automatically when the block exits, even on error. Modes: `"r"` read, `"w"` write, `"a"` append, `"b"` binary.


In [28]:

# Write
with open("scratch.txt", "w") as f:
    f.write("line 1\n")
    f.writelines(["line 2\n", "line 3\n"])

# Read whole file
with open("scratch.txt", "r") as f:
    content = f.read()
print(content)

# Read line-by-line (memory-efficient for big files)
with open("scratch.txt", "r") as f:
    for line in f:
        print(repr(line))


line 1
line 2
line 3

'line 1\n'
'line 2\n'
'line 3\n'


## Lambda Functions

Anonymous, single-expression functions. Use them where a small inline function fits better than a `def`.


In [29]:
square = lambda x: x ** 2
print(square(5))         # 25

# Most commonly used with higher-order functions:
nums = [3, 1, 4, 1, 5, 9, 2, 6]

print(sorted(nums, key=lambda x: -x))        # descending
print(list(map(lambda x: x * 2, nums)))      # doubled
print(list(filter(lambda x: x > 3, nums)))   # > 3

# Sorting dicts by value
ages = {"Alice": 30, "Bob": 25, "Cara": 35}
print(sorted(ages.items(), key=lambda kv: kv[1]))


25
[9, 6, 5, 4, 3, 2, 1, 1]
[6, 2, 8, 2, 10, 18, 4, 12]
[4, 5, 9, 6]
[('Bob', 25), ('Alice', 30), ('Cara', 35)]


## Classes: Basic Syntax

`self` is explicit — it's the first parameter of every instance method. Class attributes are shared; instance attributes are per-object.


In [30]:
class Dog:
    # Class attribute — shared by all instances
    species = "Canis familiaris"

    def __init__(self, name, age):
        # Instance attributes — unique per object
        self.name = name
        self.age = age

    def bark(self):
        return f"{self.name} says woof!"

    def birthday(self):
        self.age += 1

rex = Dog("Rex", 5)
print(rex.bark())
print(rex.species)       # via instance
print(Dog.species)       # or via class
rex.birthday()
print(rex.age)           # 6


Rex says woof!
Canis familiaris
Canis familiaris
6


# Part 2
## Basic Linear Algebra

We'll use **NumPy** to work with vectors and matrices numerically.



## Vectors: Definition

A vector is an ordered list of numbers — a point or a direction in $n$-dimensional space.

$$\vec{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix} \in \mathbb{R}^n$$


In [31]:
import numpy as np

v = np.array([3, 4])
print(v)
print("shape:", v.shape)
print("dimension:", len(v))


[3 4]
shape: (2,)
dimension: 2



## Vector Length (Norm) & Normalization

**Length** (Euclidean / $\ell_2$ norm):
$$\|\vec{v}\| = \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}$$

**Normalization** — the unit vector in the same direction:
$$\hat{v} = \frac{\vec{v}}{\|\vec{v}\|}, \qquad \|\hat{v}\| = 1$$


In [32]:
import numpy as np

v = np.array([3, 4])

length = np.linalg.norm(v)
print("length:", length)              # 5.0

unit = v / length
print("unit vector:", unit)           # [0.6 0.8]
print("its length:", np.linalg.norm(unit))  # 1.0


length: 5.0
unit vector: [0.6 0.8]
its length: 1.0



## Dot Product

$$\vec{u} \cdot \vec{v} = \sum_{i=1}^{n} u_i v_i = \|\vec{u}\|\,\|\vec{v}\|\cos\theta$$

Measures how aligned two vectors are: positive = same direction, 0 = orthogonal, negative = opposite.


In [33]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Three equivalent ways:
print(np.dot(u, v))      # 32
print(u @ v)             # 32   — the @ operator
print((u * v).sum())     # 32

# Angle between two vectors
cos_theta = (u @ v) / (np.linalg.norm(u) * np.linalg.norm(v))
print("cos theta =", cos_theta)


32
32
32
cos theta = 0.9746318461970762



## Matrices: Definition

A matrix is a 2-D array. An $m \times n$ matrix has $m$ rows and $n$ columns.

$$A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{bmatrix} \in \mathbb{R}^{2 \times 3}$$


In [34]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A)
print("shape:", A.shape)     # (2, 3)
print("A[0, 1] =", A[0, 1])  # element in row 0, col 1 -> 2
print("column 1:", A[:, 1])  # [2 5]
print("transpose:")
print(A.T)


[[1 2 3]
 [4 5 6]]
shape: (2, 3)
A[0, 1] = 2
column 1: [2 5]
transpose:
[[1 4]
 [2 5]
 [3 6]]



## Matrix Multiplication

$$(AB)_{ij} = \sum_{k} A_{ik}\, B_{kj}$$

Inner dimensions must match:
$$A \in \mathbb{R}^{m \times k},\ B \in \mathbb{R}^{k \times n} \;\Rightarrow\; AB \in \mathbb{R}^{m \times n}$$

**Watch out:** `*` in NumPy is element-wise, NOT matrix multiplication!


In [35]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("A @ B =")
print(A @ B)               # matrix multiplication

print("np.matmul:")
print(np.matmul(A, B))     # same thing

# WARNING: * is ELEMENT-wise (Hadamard), NOT matrix mult!
print("A * B (elementwise) =")
print(A * B)


A @ B =
[[19 22]
 [43 50]]
np.matmul:
[[19 22]
 [43 50]]
A * B (elementwise) =
[[ 5 12]
 [21 32]]


# Part 3
## Basic Multi-variable Derivatives

The mathematical engine behind gradient descent and backpropagation.



## Single-variable Derivative

Given a function $f(x)$, the derivative is the instantaneous rate of change:

$$\frac{df}{dx} = \lim_{h \to 0} \frac{f(x+h) - f(x)}{h}$$

**Example:** $f(x) = 3x^2 + 2x \;\Rightarrow\; \dfrac{df}{dx} = 6x + 2$



## Partial Derivatives

For $f(x_1, x_2, \dots, x_n)$, the **partial derivative** w.r.t. $x_i$ treats all other variables as constants:

$$\frac{\partial f}{\partial x_i}$$

**Example:** $f(x, y) = x^2 y + \sin(y)$

- $\dfrac{\partial f}{\partial x} = 2xy$
- $\dfrac{\partial f}{\partial y} = x^2 + \cos(y)$



## Does the Order of Differentiation Matter?

For *most* well-behaved functions, mixed partials are equal (**Clairaut's Theorem**):

$$\frac{\partial^2 f}{\partial x\, \partial y} = \frac{\partial^2 f}{\partial y\, \partial x}$$

— but continuity of the mixed partials is required.

**Classical counterexample:**

$$f(x, y) = \begin{cases} \dfrac{xy(x^2 - y^2)}{x^2 + y^2} & (x, y) \neq (0, 0) \\ 0 & (x, y) = (0, 0) \end{cases}$$

Here $f_{xy}(0, 0) = -1$ but $f_{yx}(0, 0) = +1$. **Order matters when continuity fails.**



## The Chain Rule

Composition of functions: if $z = f(y)$ and $y = g(x)$, then

$$\frac{dz}{dx} = \frac{dz}{dy} \cdot \frac{dy}{dx}$$

**Multi-variable form:** if $z = f(x, y)$ with $x = x(t)$ and $y = y(t)$,

$$\frac{dz}{dt} = \frac{\partial f}{\partial x}\frac{dx}{dt} + \frac{\partial f}{\partial y}\frac{dy}{dt}$$

> Neural networks are compositions of functions. Training them = applying the chain rule at every layer. This is **backpropagation**.



## Chain Rule: Worked Example

Let $f(x) = \sin(x^2)$. Decompose as $f = \sin(u)$ where $u = x^2$.

$$\frac{df}{dx} = \frac{df}{du}\cdot\frac{du}{dx} = \cos(u) \cdot 2x = 2x\cos(x^2)$$

Quick numerical sanity check:


In [36]:
import numpy as np

# Compare analytic derivative 2x*cos(x^2) vs. a finite-difference estimate
f = lambda x: np.sin(x ** 2)
analytic = lambda x: 2 * x * np.cos(x ** 2)

x = 1.5
h = 1e-6
numerical = (f(x + h) - f(x - h)) / (2 * h)

print("analytic :", analytic(x))
print("numerical:", numerical)


analytic : -1.8845208681682175
numerical: -1.884520868022932


# Questions?

Bring a list of anything that still feels unclear to next class.

*Next up: we start building real ML pipelines.*
